### ISSUE TITLE
Markers diseappearing on zoom in/out when updateOutBounds is set to true

### ISSUE THREAD

**Issue by sensifr** [stefanocudini/leaflet-layerJSON#1]
Hello Stefano Cudini,
It seems that there is a bug with markers: they disappear on zoom in/out when falling out of zoom bounds, you have to uncheck/check the layer to get the markers back. I only noticed the issue once implemented locally, sigh... :) 
Visible on your examples too if I except "Data by Callback".

The bug disappear if I set updateOutBounds to false.

Best regards and thank you for the script!

**Comment by rigid** [comment]
:+1:  same issue here
