### ISSUE TITLE
'async: false' and console warning

### ISSUE THREAD

**Issue by denydias** [stefanocudini/leaflet-layerJSON#15]
Hi, @stefanocudini.

First, thank you for this very useful Leaflet plugin.

Leaflet Dynamic JSON Layer [README's](https://github.com/stefanocudini/leaflet-layerJSON#options) says:

> callData alternative function that return data (if use $.ajax() set async=false)

This advice produces the expected result on `callData()`, which is to retrieve an arbitrary JSON from an arbitrary endpoint so `L.layerJSON()` render its markers correctly.

But according to [XHR Living Standard](https://xhr.spec.whatwg.org/#the-open()-method):

> Synchronous XMLHttpRequest outside of workers is in the process of being removed from the web platform as it has detrimental effects to the end user's experience. (This is a long process that takes many years.) Developers must not pass false for the async argument when entry settings object's global object is a Window object. User agents are strongly encouraged to warn about such usage in developer tools and may experiment with throwing an InvalidAccessError exception when it occurs.

This is exactly what modern browsers do. Take Chromium 53 for instance, when dynamically loading a JSON with `jQuery.ajax(url, {async: false})`, it throws at the console:

> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

When `async: true`, there are no donuts for markers though. The data required isn't there yet when `L.layerJSON()` is fired, so it has nothing to show. In that case, the JSON data is loaded asynchronously at some arbitrary moment after `window.onload()`.

We are still some years away from the day where this call is going to be promoted from a warning at the console to '*an InvalidAccessError exception*'. So maybe the time to have a closer look into it has arrived.

Is there any possibility that you could improve `callData()` so it can deal with `async: true`?

**Comment by stefanocudini** [comment]
hi @denydias 

The comment that you have mentioned was very old, it was written before I had added support for asynchronous callData functions...

However I added new example that use `jQuery.ajax()` without `async: false` and it works.
here:
http://labs.easyblog.it/maps/leaflet-layerjson/examples/jquery.html

**Comment by denydias** [comment]
Indeed, @stefanocudini! Thank you for the heads up.
