### ISSUE TITLE
function icon builder

### ISSUE THREAD

**Issue by wikimas** [stefanocudini/leaflet-layerJSON#16]
How can I add a custom icon using buildIcon? And why do the icons disappear when I define `$data['icon']='myIcon'`?

**Comment by stefanocudini** [comment]
`$data['icon']='myIcon'` WHERE?

**Comment by stefanocudini** [comment]
https://github.com/stefanocudini/leaflet-layerJSON/blob/8cc0e3eb3625ebfc366a52a6f2481b4fc9ed17b0/examples/overpass.html#L41
