### ISSUE TITLE
Deprecated include of L.Mixin.Events: this property will be removed in future releases...

### ISSUE THREAD

**Issue by mtbsomi** [stefanocudini/leaflet-layerJSON#17]
I've got this error message in Chrome, using Leaflet v1.1.0:

Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error
    at y (mydomain.com...)
    at Function.v.extend (mydomain.com...)
    at http://terkep.futonaptar.info/js/leaflet-layerjson.min.js:17:40
    at http://terkep.futonaptar.info/js/leaflet-layerjson.min.js:17:5735

Is it possible to ugrade the plugin somehow?

Thanks in advance!

**Comment by stefanocudini** [comment]
solved from version 0.2.2
