### ISSUE TITLE
OVERPASS API - Visualize way center

### ISSUE THREAD

**Issue by rmarzocchi84** [stefanocudini/leaflet-layerJSON#2]
Using overpass API I want to see also a way using the center function: 

L.layerJSON({url: 'http://overpass-api.de/api/interpreter?data=[out:json];(way({lat1},{lon1},{lat2},{lon2})[tourism=alpine_hut];);out center;',

			propertyItems: 'elements',
			propertyTitle: 'tags.name',
			propertyLoc: ['center.lat','center.lon'],

...

but it doesn't work

it produce an element Latlng (NaN,Nan)

Why?

Thanks in advanced 
R

ps: 

output json seems correct:
"version": 0.6,
  "generator": "Overpass API",
  "osm3s": {
    "timestamp_osm_base": "2014-08-20T13:00:01Z",
    "copyright": "The data included in this document is from www.openstreetmap.org. The data is made available under ODbL."
  },
  "elements": [
{
  "type": "way",
  "id": 103839515,
  "center": {
    "lat": 44.7271834,
    "lon": 9.0168653
  },
  "nodes": [
    1198725685,
    1198724829,
    1198725506,
    1198725193,
    1198725685
  ],
  "tags": {
    "building": "yes",
    "name": "Bivacco Alda e Carla Merchesotti",
    "operator": "Club Alpino Italiano - sezione di Novi Ligure",
    "tourism": "alpine_hut"
  }
},
{
  "type": "way",
  "id": 149158829,
  "center": {
    "lat": 44.4972211,
    "lon": 8.4904252
  },
  "nodes": [
    1621763986,
    1621764012,
    1621763996,
    1621763974,
    1621763987,
    1621764003,
    1621763986
  ],
  "tags": {
    "building": "yes",
    "name": "Rifugio Sciverna",
    "tourism": "alpine_hut",
    "website": "http://www.rifugiosciverna.com"
  }
},
{
  "type": "way",
  "id": 293034542,
  "center": {
    "lat": 44.7266464,
    "lon": 9.1099179
  },
  "nodes": [
    2965883248,
    2965883247,
    2965883250,
    2965883253,
    2965883252,
    2965883251,
    2965883248
  ],
  "tags": {
    "building": "yes",
    "name": "Rifugio Piani di San Lorenzo",
    "tourism": "alpine_hut"
  }
}

  ]
}

**Comment by stefanocudini** [comment]
@rmarzocchi84  per caso hai risolto in qualche modo poi?

**Comment by stefanocudini** [comment]
@rmarzocchi84  SOLVED!
